apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow
      component: scheduler
  template:
    metadata:
      labels:
        app: airflow
        component: scheduler
    spec:
      containers:
        - name: scheduler
          image: apache/airflow:2.9.3-python3.8
          ports:
            - containerPort: 8793
          volumeMounts:
            - name: airflow-data
              mountPath: /opt/airflow
      volumes:
        - name: airflow-data
          persistentVolumeClaim:
            claimName: airflow-pvc
