apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-worker
spec:
  replicas: 3
  selector:
    matchLabels:
      app: airflow
      component: worker
  template:
    metadata:
      labels:
        app: airflow
        component: worker
    spec:
      nodeSelector:
        type: worker
      containers:
        - name: worker
          image: apache/airflow:2.9.3-python3.8
          volumeMounts:
            - name: airflow-data
              mountPath: /opt/airflow
      volumes:
        - name: airflow-data
          persistentVolumeClaim:
            claimName: airflow-pvc