apiVersion: v1
kind: Service
metadata:
  name: kafka-headless
  namespace: default
spec:
  clusterIP: None  # This makes the service headless
  ports:
    - port: 9092
      name: plaintext
    - port: 9093
      name: controller
  selector:
    app: kafka

