apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        args:
        - "--kafka.server=kafka-1:9092"
        - "--kafka.server=kafka-2:9092"
        - "--kafka.server=kafka-3:9092"
        ports:
        - containerPort: 9308
        resources:
          requests:
            cpu: "250m"  
            memory: "256Mi"
          limits:
            cpu: "500m"
            memory: "512Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
spec:
  type: NodePort
  ports:
    - port: 9308
      targetPort: 9308
      nodePort: 30080
  selector:
    app: kafka-exporter
