apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-configmap
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "10.111.57.133:9092"
        topics => ["my-topic"]
        codec => plain
      }
    }
    
    output {
      file{
        path => "/usr/share/logstash/tmp/logstash.log"
      }
      elasticsearch{
        hosts => ["http://10.110.24.173:9200"]
        user => "elastic"
        password => "elastic"
        index => "kafka-logstash-%{+YYYY.MM.dd}"
      }
      stdout {
        codec => rubydebug
      }
    }
