apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash-deployment
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: elastic/logstash:7.17.24
        ports:
        - containerPort: 5044  # Logstash에서 사용하는 기본 포트
        - containerPort: 9600  # Logstash HTTP API 포트
        volumeMounts:  #현재 configmap에 두 conf파일 존재, subpath로 구분하여 따로 저장해야 함
        - name: logstash-config-volume
          mountPath: /usr/share/logstash/pipeline/kafka-collect.conf
          subPath: kafka-collect.conf
        - name: logstash-config-volume
          mountPath: /usr/share/logstash/pipeline/event-collect.conf
          subPath: event-collect.conf
      volumes:
      - name: logstash-config-volume
        configMap:
          name: logstash-configmap
---
apiVersion: v1
kind: Service
metadata:
  name: logstash-service
  labels:
    app: logstash
spec:
  ports:
  - port: 5044
    targetPort: 5044
    protocol: TCP
  selector:
    app: logstash
