apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-deployment
  labels:
    app: spark
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark
      role: master
  template:
    metadata:
      labels:
        app: spark
        role: master
    spec:
      containers:
      - name: spark-master-container
        image: apache/spark:3.5.1
        ports:
        - containerPort: 7077
        - containerPort: 4040
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: workflow 
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_SECRET_ACCESS_KEY
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: workflow
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workflow
              key: POSTGRES_PASSWORD
        - name: SPARK_LOCAL_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
            #- name: SPARK_WORKER_INSTANCES
            #value: "3"
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"] 
        args: ["--host", "$(SPARK_LOCAL_IP)", "--port", "7077", "--webui-port", "8080"]
        volumeMounts:
        - name: spark-jars-volume
          mountPath: /opt/spark/jars
        - name: spark-jobs-volume
          mountPath: /opt/spark/work-dir
        resources:
          requests:
            cpu: "1000m"
            memory: "4Gi"
          limits:
            cpu: "1000m"
            memory: "4Gi"
      volumes:
      - name: spark-jars-volume
        persistentVolumeClaim:
          claimName: spark-jars-pvc
      - name: spark-jobs-volume
        persistentVolumeClaim:
          claimName: spark-jobs-pvc

      #nodeSelector:
        #type: master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service   ##!!!!반드시!!! spark-master라고 하면 안됨. spark가 사용하는 환경변수 이름이 SPARK_MASTER_PORT인데, 서비스 이름을 spark-master라고 지정하면 쿠버네티스도 같은 이름으로 다른 내용의 변수를 생성
  labels:
    app: spark
spec:
  type: NodePort
  ports:
  - name: spark-master-port
    port: 7077
    targetPort: 7077
    nodePort: 32077
  - name: spark-master-ui
    port: 8080 
    targetPort: 8080
    nodePort: 32080
  - name: spark-master-ui2
    port: 4040
    targetPort: 4040
    nodePort: 32040
  selector:
    app: spark
    role: master
