# 백업 테스트용
apiVersion: v1
kind: Pod
metadata:
  name: backup-check
spec:
  containers:
  - name: backup-check
    image: busybox
    command: ['sh', '-c', 'ls -l /backup && tail -n 5 /backup/*']
    volumeMounts:
    - name: backup-volume
      mountPath: /backup
  volumes:
  - name: backup-volume
    persistentVolumeClaim:
      claimName: postgres-backup-pvc
