apiVersion: v1
kind: Service
metadata:
  name: postgres-exporter-external
spec:
  type: NodePort
  ports:
  - port: 9187
    targetPort: 9187
    nodePort: 30000
  selector:
    app: postgres-exporter
