# 임시 테스트용 파일.
apiVersion: v1
kind: Pod
metadata:
  name: psql-client
spec:
  containers:
  - name: psql-client
    image: postgres:15
    command: ['sleep', '3600']
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-secret
          key: POSTGRES_PASSWORD
