apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: user-storage-class
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
  fsType: ext4
reclaimPolicy: Delete
volumeBindingMode: Immediate
