# Use an official Python runtime as a parent image
FROM python:3.11.9-slim

# Set the working directory in the container
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    librdkafka-dev \
    && rm -rf /var/lib/apt/lists/*

# Install Python dependencies
RUN pip install --no-cache-dir confluent-kafka pyspark boto3

# Copy your Kafka producer script to the container
COPY ConfluentKafkaProducer.py /app/ConfluentKafkaProducer.py
COPY sparkScript.py /app/s3Script.py
# Set the default command to run the script
CMD ["python", "/app/ConfluentKafkaProducer.py"]
CMD ["spark-submit", "/app/s3Script.py"]
CMD ["tail", "-f", "/dev/null"]
