---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-config
  namespace: system
spec:
  addresses:
  - 172.31.31.331-172.31.31.341
  autoAssign: true
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: metallb-config
  namespace: system
spec:
  ipAddressPools:
    - metallb-config
