apiVersion: apps/v1
kind: Deployment
metadata:
  name: metallb-controller
  namespace: system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metallb
      component: controller
  template:
    metadata:
      labels:
        app: metallb
        component: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: quay.io/metallb/controller:latest
        ports:
        - containerPort: 7472
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: metallb-speaker
  namespace: system
spec:
  selector:
    matchLabels:
      app: metallb
      component: speaker
  template:
    metadata:
      labels:
        app: metallb
        component: speaker
    spec:
      serviceAccountName: speaker
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:latest
        ports:
        - containerPort: 7472
      hostNetwork: true
---
apiVersion: v1
kind: Service
metadata:
  name: metallb-webhook-service
  namespace: system
spec:
  selector:
    app: metallb
    component: controller
  ports:
  - port: 7472
    targetPort: 7472
