# ---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: metallb-system

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: controller
#   namespace: metallb-system

# ---
# apiVersion: v1
# kind: ServiceAccount
# metadata:
#   name: speaker
#   namespace: metallb-system

# ---
#apiVersion: rbac.authorization.k8s.io/v1
#kind: ClusterRole
#metadata:
#   name: metallb-system:controller
# rules:
# - apiGroups: [""]
#   resources: ["services", "endpoints", "nodes", "secrets", "configmaps"]
#   verbs: ["get", "list", "watch", "create", "update", "patch"]

# ---
# apiVersion: rbac.authorization.k8s.io/v1
# kind: ClusterRoleBinding
# metadata:
#   name: metallb-system:controller
# roleRef:
#   apiGroup: rbac.authorization.k8s.io
#   kind: ClusterRole
#   name: metallb-system:controller
# subjects:
# - kind: ServiceAccount
#   name: controller
#   namespace: metallb-system

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller
  namespace: metallb-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: controller
  template:
    metadata:
      labels:
        component: controller
    spec:
      serviceAccountName: controller
      containers:
      - name: controller
        image: quay.io/metallb/controller:main
        args:
        - --port=7472
        ports:
        - containerPort: 7472
          name: monitoring

---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speaker
  namespace: metallb-system
spec:
  selector:
    matchLabels:
      component: speaker
  template:
    metadata:
      labels:
        component: speaker
    spec:
      serviceAccountName: speaker
      hostNetwork: true
      containers:
      - name: speaker
        image: quay.io/metallb/speaker:main
        args:
        - --port=7472
        env:
        - name: METALLB_NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: METALLB_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: METALLB_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP

        ports:
        - containerPort: 7472
          name: monitoring

