apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: mongodb
  replicas: 2
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.18
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"
            - "--replSet"
            - "MainRepSet"
            - "--setParameter"
            - "authenticationMechanisms=SCRAM-SHA-1"
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: mongodb-storage
              mountPath: /data  # MongoDB의 데이터 디렉토리
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  # 생성한 Secret의 이름
                  key: MONGO_INITDB_ROOT_USERNAME  # Secret의 키
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret  # 생성한 Secret의 이름
                  key: MONGO_INITDB_ROOT_PASSWORD  # Secret의 키
      initContainers:
        - name: mongo-init-replica
          image: mongo:4.4.18
          command: ['sh', '-c', 'mongo --eval "rs.initiate()"']

  volumeClaimTemplates:
    - metadata:
        name: mongodb-storage  # PVC 이름
      spec:
        accessModes: 
          - ReadWriteMany
        resources:
          requests:
            storage: 1Gi
        storageClassName: efs-sc  # StorageClass 추가
