apiVersion: v1
kind: Pod
metadata:
  labels:
    version: "3.5.1"
spec:
  nodeSelector:
    type: worker
  containers:
    - name: spark-kubernetes-driver
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_SECRET_ACCESS_KEY
      resources:
        requests:
          memory: "500Mi"
          cpu: "300m"
        limits:
          memory: "1Gi"
          cpu: "1"
      volumeMounts:
        - name: history-volume
          mountPath: /mnt/spark-history-logs
  volumes:
    - name: history-volume
      persistentVolumeClaim:
        claimName: sparkhistoryserver-pvc
