apiVersion: v1
kind: Pod
metadata:
  labels:
    version: "3.5.2"
spec:
  containers:
    - name: spark-kubernetes-executor
      env:
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_SECRET_ACCESS_KEY
      resources:
        requests:
          memory: "2Gi"
          cpu: "1"
        limits:
          memory: "4Gi"
          cpu: "2"
      volumeMounts:
        - name: history-volume
          mountPath: /mnt/spark-history-logs
  volumes:
    - name: history-volume
      persistentVolumeClaim:
        claimName: sparkhistoryserver-pvc
