apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi-container
        image: loafingcat/fastapi-app:1.0
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "256Mi" 
            cpu: "250m"    
          limits:
            memory: "512Mi"
            cpu: "500m"
        env:  # 환경 변수를 추가합니다.
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: workflow  # Secret 이름
              key: AWS_ACCESS_KEY_ID  # Secret의 키
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_SECRET_ACCESS_KEY
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-service
spec:
  type: NodePort
  ports:
  - port: 8000        # 외부에서 접근할 포트
    targetPort: 8000  # 컨테이너 내의 포트
    nodePort: 31949   # 노드에서 사용할 포트 (명시적으로 설정)
  selector:
    app: fastapi
