apiVersion: v1
kind: PersistentVolume
metadata:
  name: airflow-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: airflow-storageclass
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00fb81d888c7ed27c  # 사용 중인 EFS 파일 시스템 ID

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: airflow-storageclass
  resources:
    requests:
      storage: 1Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: airflow-storageclass
  resources:
    requests:
      storage: 1Gi