apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-worker
  labels:
    app: spark
spec:
  replicas: 3
  selector:
    matchLabels:
      app: spark
      role: worker
  template:
    metadata:
      labels:
        app: spark
        role: worker
    spec:
      containers:
      - name: spark-worker
        image: bitnami/spark:latest
        ports:
        - containerPort: 8081
        env:
        - name: SPARK_MODE
          value: worker
        - name: SPARK_MASTER_URL
          value: spark://spark-master:7077
---
apiVersion: v1
kind: Service
metadata:
  name: spark-worker
  labels:
    app: spark
spec:
  type: ClusterIP
  ports:
  - name: spark-worker-ui
    port: 8081
    targetPort: 8081
  selector:
    app: spark
    role: worker
