apiVersion: apps/v1
kind: Deployment
metadata:
  name: spark-master-test
  labels:
    app: spark-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spark-test
      role: master
  template:
    metadata:
      labels:
        app: spark-test
        role: master
    spec:
      containers:
      - name: spark-master-container-test
        image: sparktestimage:latest
        ports:
        - containerPort: 7077
        - containerPort: 8080
        env:
        - name: SPARK_MODE
          value: "master"
        - name: SPARK_MASTER_WEBUI_PORT
          value: "8080"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: workflow 
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: workflow
              key: AWS_SECRET_ACCESS_KEY
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: workflow
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: workflow
              key: POSTGRES_PASSWORD
            #- name: SPARK_WORKER_INSTANCES
            #value: "3"
        command: ["/opt/spark/bin/spark-class", "org.apache.spark.deploy.master.Master"] 
        args: ["--host", "0.0.0.0", "--port", "7077", "--webui-port", "8080"]
        resources:
          requests:
            cpu: "500m"
            memory: "1Gi"
          limits:
            cpu: "1"
            memory: "2Gi"
      #nodeSelector:
        #type: master
---
apiVersion: v1
kind: Service
metadata:
  name: spark-master-service-test   ##!!!!반드시!!! spark-master라고 하면 안됨. spark가 사용하는 환경변수 이름이 SPARK_MASTER_PORT인데, 서비스 이름을 spark-master라고 지정하면 쿠버네티스도 같은 이름으로 다른 내용의 변수를 생성
  labels:
    app: spark-test
spec:
  type: NodePort
  ports:
  - name: spark-master-port-test
    port: 7077
    targetPort: 7077
    nodePort: 32077
  - name: spark-master-ui-test
    port: 8080
    targetPort: 8080
    nodePort: 32080
  selector:
    app: spark-test
    role: master
