#쿠버네티스 이벤트를 수집하여 로그스태시에 보내기 위한filebeat yaml configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: filebeat-config
data:
  filebeat.yml: |
    filebeat.inputs:
    - type: log
      paths:
        - /var/log/containers/*.log  #Kubernetes 컨테이너 로그가 저장되는 경로 !
      processors:
      - add_kubernetes_metadata:  #로그에 추가적인 메타데이터 (파드 이름, 네임 스페이스, 컨테이너 이름 등 ) 포함시키는 역할, 메타데이터는 쿠버네티스 API서버에서 관리하므로 클러스터 내부에서 실행되어야 함
          in_cluster: true  #true로 설정 시 Kubernetes API 서버에 접근하여 메타 데이터를 가져옴! (클러스터 내부에서 실행되는 파드로 간주, ServiceAccount에 의해 API서버에 인증됨) false로 설정시 수동으로 자격증명을 해야함

    output.logstash:
      hosts: ["logstash-service:5044"]
