apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
data:
  logstash.conf: |
    input {
      kafka {
        bootstrap_servers => "kafka-1:9092"
        topics => ["my-topic"]
      }
    }
    
    output {
      stdout {}
    }
