apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:   # Alertmanager와 연동
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager:9093'
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

  alert.rules: |  # 알람 규칙 파일 추가
    groups:
      - name: server-down-alert
        rules:
        - alert: ServerDown
          expr: up == 0
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Server {{ $labels.instance }} is down"
            description: "The server at {{ $labels.instance }} has been down for more than 1 minute."
