apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    alerting:
      alertmanagers:
      - static_configs:
        - targets:
          - 'alertmanager:9093'
    
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']

      - job_name: 'postgres-exporter'  # PostgreSQL Exporter 추가
        static_configs:
        - targets: ['postgres-exporter:9187']  # PostgreSQL Exporter 서비스 이름과 포트

      - job_name: 'kafka-exporter'  # Kafka Exporter 추가
        static_configs:
        - targets: ['kafka-exporter:9308']  # Kafka Exporter 서비스 이름과 포트

      - job_name: 'kafka-jmx'  # Kafka Exporter 추가
        static_configs:
        - targets: ['jmx-exporter:7071']

      - job_name: 'redis-exporter'
        static_configs:
        - targets: ['redis-exporter:9121']

      - job_name: 'mongodb-exporter'  # MongoDB Exporter 추가
        static_configs:
        - targets: ['mongodb-exporter:9216']

      - job_name: 'elasticsearch-exporter'  # Elasticsearch Exporter 추가
        static_configs:
        - targets: ['elasticsearch-exporter:9114']

  alert.rules: |
    groups:
      - name: server-down-alert
        rules:
          - alert: PostgresDown
            expr: pg_up == 0
            for: 1m
            labels:
              severity: critical
            annotations:
              summary: "PostgreSQL instance is down"
              description: "PostgreSQL instance {{ $labels.instance }} is down."

        # - alert: ServerDown
        #   expr: up == 0
        #   for: 1m
        #   labels:
        #     severity: critical
        #   annotations:
        #     summary: "Server {{ $labels.instance }} is down"
        #     description: "The server at {{ $labels.instance }} has been down for more than 1 minute."