apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      securityContext:
        fsGroup: 65534  # 파일 시스템 그룹은 Pod 수준에서 설정
        runAsUser: 1000  # 컨테이너가 1000 UID로 실행
        runAsGroup: 1000  # 컨테이너가 1000 GID로 실행
      initContainers:
      - name: init-config
        image: busybox
        command: ["/bin/sh", "-c"]
        args:
          - |
            cp /tmp/alertmanager/alertmanager.yml /etc/alertmanager/alertmanager.yml
            sed -i "s|SLACK_WEBHOOK_URL_PLACEHOLDER|$SLACK_WEBHOOK_URL|g" /etc/alertmanager/alertmanager.yml
        env:
        - name: SLACK_WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: alertmanager-secrets
              key: SLACK_WEBHOOK_URL
        volumeMounts:
        - name: config-volume
          mountPath: /tmp/alertmanager
        - name: alertmanager-config
          mountPath: /etc/alertmanager
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        args:
        - "--config.file=/etc/alertmanager/alertmanager.yml"
        - "--storage.path=/alertmanager"
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        - name: storage-volume
          mountPath: /alertmanager
      volumes:
      - name: config-volume
        configMap:
          name: alertmanager-config
      - name: alertmanager-config
        emptyDir: {}
      - name: storage-volume
        persistentVolumeClaim:
          claimName: alertmanager-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  type: NodePort
  selector:
    app: alertmanager
  ports:
    - port: 9093
      targetPort: 9093
      nodePort: 32111
