apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: postgres-psp
spec:
  privileged: false
  seLinux:
    rule: RunAsAny
  supplementalGroups:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 999
  runAsUser:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 999
  fsGroup:
    rule: MustRunAs
    ranges:
      - min: 999
        max: 999
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  - 'persistentVolumeClaim'

---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: postgres-network-policy
spec:
  podSelector:
    matchLabels:
      app: postgres-cluster
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          access-postgres: "true"
    ports:
    - protocol: TCP
      port: 5432
  egress:
  - to:
    - podSelector: {}
    ports:
    - protocol: TCP
      port: 5432
