---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: mlops
  POSTGRES_USER: mlops_user
  POSTGRES_CONFIG: |
    max_connections = 100
    shared_buffers = 256MB
    wal_level = replica
    max_wal_senders = 10

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: patroni-config
data:
  PATRONI_SCOPE: postgres-cluster
  PATRONI_KUBERNETES_NAMESPACE: default
  PATRONI_KUBERNETES_LABELS: '{application: postgres}'
  PATRONI_SUPERUSER_USERNAME: postgres
  PATRONI_REPLICATION_USERNAME: replicator
  PATRONI_POSTGRESQL_LISTEN: 0.0.0.0:5432
  PATRONI_RESTAPI_LISTEN: 0.0.0.0:8008

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
    csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00fb81d888c7ed27c

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: efs-sc

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-cluster
spec:
  serviceName: postgres-cluster
  replicas: 2
  selector:
    matchLabels:
      app: postgres-cluster
  template:
    metadata:
      labels:
        app: postgres-cluster
    spec:
      securityContext:
        fsGroup: 999
        runAsUser: 999
        runAsGroup: 999
      containers:
      - name: postgres
        image: postgres:13
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 1
            memory: 2Gi
        ports:
        - containerPort: 5432
        - containerPort: 8008
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data
          subPath: pgdata
      - name: patroni
        image: registry.opensource.zalan.do/acid/patroni:2.0.2
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 200m
            memory: 512Mi
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_PASSWORD
        - name: POSTGRES_REPLICATION_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_REPLICATION_PASSWORD
        envFrom:
        - configMapRef:
            name: patroni-config
        - configMapRef:
            name: postgres-config
        ports:
        - containerPort: 8008
  volumeClaimTemplates:
  - metadata:
      name: pgdata
    spec:
      accessModes: ["ReadWriteMany"]
      storageClassName: efs-sc
      resources:
        requests:
          storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster
spec:
  selector:
    app: postgres-cluster
  ports:
  - port: 5432
    targetPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cluster-headless
spec:
  clusterIP: None
  selector:
    app: postgres-cluster
  ports:
  - port: 5432
    targetPort: 5432