---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres 
spec:
  serviceName: "postgres"
  replicas: 1 
  selector:
    matchLabels:
      app: postgres 
  template:
    metadata:
      labels:
        app: postgres 
    spec:
      securityContext:
        runAsUser: 999
        fsGroup: 999
      containers:
        - name: postgres
          image: postgres:13 
          command: ["/bin/bash", "-c"]
          args:
            - |
              if [ ! -s "$PGDATA/PG_VERSION" ]; then
                echo "Initializing database..."
                initdb -D "$PGDATA"
              fi
              echo "Starting PostgreSQL..."
              exec postgres
          volumeMounts:
            - name: postgres-storage 
              mountPath: /var/lib/postgresql/data 
          ports:
            - containerPort: 5432 
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data
          envFrom:
            - secretRef:
                name: db 
          resources:
            requests:
              cpu: 500m 
              memory: 1Gi 
            limits:
              cpu: 1 
              memory: 2Gi 
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc-postgres-0
---
apiVersion: v1 
kind: Service 
metadata:
  name: postgres 
spec:
  selector:
    app: postgres 
  ports:
    - protocol: TCP 
      port: 5432 
      targetPort: 5432
  clusterIP: None  

