# EBS를 사용하는 StorageClass 정의 (이미 존재하는 경우 생략 가능)
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ebs-gp3
provisioner: ebs.csi.aws.com # AWS EBS CSI 드라이버 사용
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Retain
parameters:
  type: gp3 # EBS 볼륨 유형
  fsType: ext4 # 파일 시스템 유형

---
# EFS를 사용하는 StorageClass 정의
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: efs-sc  # StorageClass 이름
provisioner: efs.csi.aws.com  # EFS CSI 드라이버 사용
allowVolumeExpansion: true  # EFS는 확장 가능
volumeBindingMode: Immediate  # PVC 생성 시 즉시 바인딩
reclaimPolicy: Delete  # PVC 삭제 시 데이터는 유지


