apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-readonly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-readonly
  template:
    metadata:
      labels:
        app: postgres-readonly
    spec:
      containers:
      - name: postgres
        image: postgres:13
        command: ["/bin/sh"]
        args: ["-c", "echo \"hot_standby = on\" >> /var/lib/postgresql/data/postgresql.conf && docker-entrypoint.sh postgres -c config_file=/var/lib/postgresql/data/postgresql.conf"]
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: POSTGRES_PASSWORD
        envFrom:
        - configMapRef:
            name: postgres-config

---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: postgres-readonly-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: postgres-readonly
  minReplicas: 1
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 50

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-readonly
spec:
  selector:
    app: postgres-readonly
  ports:
    - port: 5432
