apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch-exporter
  template:
    metadata:
      labels:
        app: elasticsearch-exporter
    spec:
      containers:
      - name: elasticsearch-exporter
        image: justwatch/elasticsearch_exporter:latest
        ports:
        - containerPort: 9108  # Elasticsearch Exporter의 기본 포트
        env:
        - name: ELASTICSEARCH_URL
          value: "http://elasticsearch:9200"  # Elasticsearch 서비스 주소
---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch-exporter
  labels:
    app: elasticsearch-exporter
spec:
  ports:
  - name: metrics
    port: 9108
    targetPort: 9108
  selector:
    app: elasticsearch-exporter
  type: ClusterIP
