apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      containers:
      - name: filebeat
        image: elastic/filebeat:7.17.24
        volumeMounts:
        - name: config
          mountPath: /usr/share/filebeat/filebeat.yml
          subPath: filebeat.yml  #configmap yaml 파일 내에 여러 데이터가 있어도 이 이름에 해당하는 데이터만 마운트 함. 즉 configmap 내 filebeat.yml 설정만 가져와서 마운트하기 위한 옵션
        env:
        - name: NODE_NAME  # 현재 파드가 실행되고 있는 노드의 이름을 환경변수로 지정
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: config
        configMap:
          name: filebeat-config  #configmap 경로 : ../../resources/configmap/filebeat-cm.yaml
