apiVersion: v1
kind: PersistentVolume
metadata:
  name: alertmanager-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # EFS는 여러 pod가 동시에 접근할 수 있으므로 ReadWriteMany 사용
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00fb81d888c7ed27c::fsap-078267eb689cce572  # EFS 파일 시스템 ID와 파일 시스템 액세스 포인트 ID
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: alertmanager-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  volumeName: alertmanager-pv  # 위에서 정의한 PV를 참조
