apiVersion: v1
kind: PersistentVolume
metadata:
  name: prometheus-pv
spec:
  capacity:
    storage: 20Gi  # 필요한 스토리지 용량을 설정
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # 여러 노드에서 읽고 쓸 수 있음
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-00fb81d888c7ed27c  # EFS 파일 시스템 ID
    volumeAttributes:
      path: /prometheus  # EFS 내 마운트 경로
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prometheus-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi  # 필요한 스토리지 요청
  volumeName: prometheus-pv
