apiVersion: v1
kind: Service
metadata:
  name: redis-cluster
  labels:
    app: redis
spec:
  ports:
    - port: 6379
      name: redis
  clusterIP: None # Headless Service 설정
  selector:
    app: redis
