apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-cluster
spec:
  serviceName: redis
  replicas: 3  # 마스터 노드 3개로 구성
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      dnsPolicy: ClusterFirst  # 쿠버네티스 클러스터의 DNS 사용
      nodeSelector:
        type: worker  # worker 노드에 배포
      containers:
        - name: redis
          image: redis:6.2  # Redis 버전 지정
          ports:
            - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-storage
          command:
            - "redis-server"
          args:
            - "--cluster-enabled"      # 클러스터 모드 활성화
            - "yes"
            - "--cluster-config-file"   # 클러스터 설정 파일 경로
            - "/data/nodes.conf"
            - "--cluster-node-timeout"  # 타임아웃 설정
            - "5000"
            - "--appendonly"
            - "yes"
            - "--appendfsync"
            - "everysec"
            - "--save"
            - "900 1"
            - "--save"
            - "300 10"
            - "--save"
            - "60 10000"
            - "--dir"
            - "/data"
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc
  volumeClaimTemplates:
    - metadata:
        name: redis-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: redis-storageclass
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  ports:
    - protocol: TCP
      port: 6379
  clusterIP: None  # StatefulSet의 각 파드에 고유한 DNS 이름 부여
  selector:
    app: redis
