apiVersion: v1
kind: ConfigMap
metadata:
  name: jmx-exporter-config
data:
  config.yaml: |
    rules:
      - pattern: "kafka.server<type=(.+), name=(.+)><>\\w+"
        name: kafka_$1_$2
        labels:
          topic: "$3"
