apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mongodb
spec:
  serviceName: "mongodb"
  replicas: 2  # MongoDB 인스턴스 수
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        type: worker  # worker 노드에 배포
      tolerations:                
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
        - name: mongodb
          image: mongo:4.4.18
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MONGO_INITDB_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MONGO_INITDB_ROOT_PASSWORD
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db
                  key: MONGO_INITDB_DATABASE
          command:
            - "numactl"
            - "--interleave=all"
            - "mongod"
            - "--bind_ip"
            - "0.0.0.0"  # 모든 IP에서 접근 가능
            - "--replSet"
            - "MainRepSet"  # ReplicaSet 이름
            - "--setParameter"
            - "authenticationMechanisms=SCRAM-SHA-1"  # 인증 메커니즘 설정
            - "--dbpath"
            - "/mongo"  # EFS에 마운트된 PVC 경로
          volumeMounts:
            - name: mongo-storage
              mountPath: /mongo  # PVC가 /mongo 경로에 마운트됨
          ports:
            - containerPort: 27017
  volumeClaimTemplates:
    - metadata:
        name: mongo-storage  # StatefulSet에서 생성할 고유한 PVC 이름
      spec:
        accessModes:
          - ReadWriteOnce  # 각 Pod에서만 읽기/쓰기 가능
        storageClassName: mongo-storageclass  # 수정된 StorageClass 사용 (EFS)
        resources:
          requests:
            storage: 1Gi  # 요청하는 스토리지 크기
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb  # StatefulSet에서 사용할 서비스 이름
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017  # MongoDB 기본 포트
      name: mongo
  clusterIP: None  # Headless Service로 설정하여 ClusterIP를 사용하지 않음
  selector:
    app: mongodb  # StatefulSet의 Pod를 선택
