apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-efs-claim
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi  # 요청하는 스토리지 크기
  storageClassName: es-storageclass  # 사용 중인 StorageClass 이름

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  serviceName: "elasticsearch"
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      nodeSelector:
        type: worker
      tolerations:                
        - key: "node.kubernetes.io/not-ready"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
        - key: "node.kubernetes.io/unreachable"
          operator: "Exists"
          effect: "NoExecute"
          tolerationSeconds: 30
      containers:
      - name: elasticsearch
        image: elastic/elasticsearch:7.17.24
        env:
        - name: ELASTIC_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db
              key: ELASTICSEARCH_PASSWORD
        - name: xpack.security.enabled
          value: "true"
        - name: xpack.security.transport.ssl.enabled
          value: "true"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-0"
        - name: network.host
          value: "0.0.0.0"
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elastic-volume
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elastic-volume
        persistentVolumeClaim:
          claimName: elasticsearch-efs-claim  # PVC 이름

---
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  ports:
  - name: elasticsearch
    port: 9200
    targetPort: 9200
  - name: elastic-transport
    port: 9300
    targetPort: 9300
  selector:
    app: elasticsearch
  type: ClusterIP
