apiVersion: v1 
kind: PersistentVolume 
metadata:
  name: postgres-pv
spec:
  capacity:
    storage: 1Gi 
  volumeMode: Filesystem 
  accessModes:
    - ReadWriteMany 
  persistentVolumeReclaimPolicy: Retain 
  storageClassName: efs-sc 
  claimRef:
    namespace: default
    name: postgres-pvc-postgres-0
  csi:
    driver: efs.csi.aws.com 
    volumeHandle: fs-00fb81d888c7ed27c 
---
apiVersion: v1 
kind: PersistentVolumeClaim 
metadata:
  name: postgres-pvc-postgres-0 
spec:
  accessModes:
    - ReadWriteMany 
  storageClassName: efs-sc 
  resources:
    requests:
      storage: 1Gi 
