cversion: '3.8'

services:
  db:
    image: mysql:8.4.2
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword  # secrets 대신 직접 비밀번호 설정
      MYSQL_DATABASE: myproject
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      TZ: "Asia/Seoul"
      MYSQL_CHARACTER_SET_SERVER: "utf8mb4"
      MYSQL_COLLATION_SERVER: "utf8mb4_unicode_ci"
      MYSQL_INNODB_BUFFER_POOL_SIZE: "512M"
      MYSQL_INNODB_LOG_FILE_SIZE: "128M"
      MYSQL_MAX_CONNECTIONS: "500"
    ports:
      - "22130:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./logs:/var/log/mysql
    networks:
      - backend
    command:
      - --default-authentication-plugin=mysql_native_password
      - --explicit_defaults_for_timestamp=1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  backend:
    driver: bridge

volumes:
  mysql_data:
    driver: local
