version: '3.8'

services:
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - "24093:6379"
    volumes:
      - redis-data:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    environment:
      - REDIS_MAXMEMORY=${REDIS_MAXMEMORY}
      - REDIS_MAXMEMORY_POLICY=${REDIS_MAXMEMORY_POLICY}
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: redis-commander
    environment:
      - REDIS_HOSTS=${REDIS_COMMANDER_HOST}
    ports:
      - "8081:8081"
    depends_on:
      - redis

volumes:
  redis-data: