name: Notify Slack on Branch Commits

on:
  push:
    branches:
      - instance1
      - instance4
      - mlops
      - main

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_MESSAGE: "New commit pushed to ${{ github.ref }} by ${{ github.actor }}: ${{ github.event.head_commit.message }}"